/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jaypr
 */
public class teacher_window extends javax.swing.JFrame {

    /**
     * Creates new form teacher_window
     */
    public teacher_window() {
        initComponents();
        getMySqlConnection();
        fillTable(); // fillTable() called to display  the data once the teacher form gets loaded.
    }
     
    
    public Connection getMySqlConnection(){
        Connection conn=null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/jay1",
                    "root", "root");
//            JOptionPane.showMessageDialog(null, "Mysql DB Connection Successful...");
            return conn;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Mysql Connection Failed.... error"+e);
            return null;
        }    
    } 
    
   
    
    // show and add data to the table
    public ArrayList<teacher_bean> getAllteacherData(){
        ArrayList<teacher_bean> al=null;
                al=new ArrayList<teacher_bean>();
       
        try {
            Connection conn=getMySqlConnection();
            String qry="select * from teacher";
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery(qry);
            teacher_bean teacher;
            while (rs.next()) {
                teacher =new teacher_bean(Integer.parseInt(rs.getString(1)),rs.getString("name"),
                        Float.parseFloat(rs.getString(3)), rs.getString(4), rs.getString("address"),
                        rs.getString(6));                
                al.add(teacher);
                
              }
            if (st!=null){
                    st.close();
                }
            if (conn!=null){
                    conn.close();
                }
            
           
        } catch (Exception e) {
            System.out.println("Error in getAllteacherdata"+e);
        }
       return al; 
    }
    //fill the table with the data
    public void fillTable(){
        ArrayList<teacher_bean> al=getAllteacherData();
        DefaultTableModel model=(DefaultTableModel)jTable.getModel();
        model.setRowCount(0); // Empty/clear the table
        Object[] row=new Object[6];
        for (int i = 0; i < al.size(); i++) {
            row[0]=al.get(i).getId();
            row[1]=al.get(i).getName();
            row[2]=al.get(i).getSalary();
            row[3]=al.get(i).getDob();
            row[4]=al.get(i).getAddress();
            row[5]=al.get(i).getSubject();
            model.addRow(row);
        }
        //model.setRowCount(0);
    }
    
    
    //Show item/data to fields in the form of teacher
    public void showItemToFields(int index){
        jTextField1_id.setText(Integer.toString(getAllteacherData().get(index).getId()));
        jTextField2_name.setText(getAllteacherData().get(index).getName());
        jTextField3_salary.setText(Float.toString(getAllteacherData().get(index).getSalary()));
        
        try {
            java.util.Date dob=null;
            dob=new SimpleDateFormat("dd-MM-yyyy").parse((String)getAllteacherData().get(index).getDob());
            jDateChooser1_dob.setDate(dob);          
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "error show item to field"+e);
                     
         }
        jTextArea1_address.setText(getAllteacherData().get(index).getAddress());  
        jTextField4_subject.setText(getAllteacherData().get(index).getSubject());       
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1_id = new javax.swing.JTextField();
        jTextField2_name = new javax.swing.JTextField();
        jTextField3_salary = new javax.swing.JTextField();
        jDateChooser1_dob = new com.toedter.calendar.JDateChooser();
        jTextField4_subject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1_address = new javax.swing.JTextArea();
        jButton1_new = new javax.swing.JButton();
        jButton2_save = new javax.swing.JButton();
        jButton3_update = new javax.swing.JButton();
        jButton4_delete = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField1_search = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Bundelkhand University, Jhansi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 153));
        jLabel2.setText("Computer Science and Engineering");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 153));
        jLabel3.setText("Teacher Information");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Teacher id :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Teacher Salary :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Date of Birth :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("address :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Subject :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("Teacher Name :");

        jDateChooser1_dob.setDateFormatString("dd-MM-yyyy");

        jTextArea1_address.setColumns(20);
        jTextArea1_address.setRows(5);
        jScrollPane1.setViewportView(jTextArea1_address);

        jButton1_new.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1_new.setText("New/Clear");
        jButton1_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_newActionPerformed(evt);
            }
        });

        jButton2_save.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2_save.setText("Save/Insert");
        jButton2_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_saveActionPerformed(evt);
            }
        });

        jButton3_update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3_update.setText("Update");
        jButton3_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_updateActionPerformed(evt);
            }
        });

        jButton4_delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4_delete.setText("Delete");
        jButton4_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_deleteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Search the faculty by their name :");

        jTextField1_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1_searchKeyReleased(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Teacher Id", "Teacher Name", "Salary", "DOB", "Address", "Subject"
            }
        ));
        jTable.getTableHeader().setReorderingAllowed(false);
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1_new))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1_search, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton2_save)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                                .addComponent(jButton3_update))
                                            .addComponent(jTextField3_salary)
                                            .addComponent(jTextField2_name))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel7))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton4_delete)
                                                .addGap(10, 10, 10))))
                                    .addComponent(jTextField1_id, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateChooser1_dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField4_subject)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)
                        .addComponent(jTextField1_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser1_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jTextField2_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTextField4_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField3_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4_delete)
                            .addComponent(jButton3_update)
                            .addComponent(jButton2_save)
                            .addComponent(jButton1_new))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1_search, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // save or insert the teacher details
    private void jButton2_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_saveActionPerformed
        // TODO add your handling code here:
        if (jTextField1_id.getText().toString().equals("") ||
            jTextField2_name.getText().toString().equals("") || 
            jTextField3_salary.getText().toString().equals("") ||
            jTextField4_subject.getText().toString().equals("") ||
            jTextArea1_address.getText().toString().equals("")
            )
            
        {
            JOptionPane.showMessageDialog(null, "all fields are compulsary");
        }
        else{
            try{
                Connection conn=getMySqlConnection();
                String query="insert into teacher (id,name,salary,dob,address,subject) values (?,?,?,?,?,?)";
                PreparedStatement ps=conn.prepareStatement(query);
                ps.setInt(1, Integer.parseInt(jTextField1_id.getText().toString()));
                ps.setString(2,jTextField2_name.getText().toString());
                ps.setFloat(3, Float.parseFloat(jTextField3_salary.getText().toString()));
                
                SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
                String dob1=sdf.format(jDateChooser1_dob.getDate());
                ps.setString(4,dob1);
                
                ps.setString(5,jTextArea1_address.getText().toString());
                ps.setString(6,jTextField4_subject .getText().toString());
                
                
                
                
                int res=ps.executeUpdate();
                fillTable();// fillTable() call to display the data after newly insertred teacher in table
                if (res>=1) {
                    JOptionPane.showMessageDialog(null, res+"teacher saved successfully to database");
                }else{
                    JOptionPane.showMessageDialog(null, "teacher Insertion Failed ....");
                }
                if (ps!=null){
                    ps.close();
                }
                if (conn!=null){
                    conn.close();
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "error : "+e);
            }       
            // clear the fileds
            jTextField1_id.setText("");
            jTextField2_name.setText("");
            jTextField3_salary.setText("");
            jTextField4_subject.setText("");
            jDateChooser1_dob.setDate(null);
            jTextArea1_address.setText("");
            
        }
    }//GEN-LAST:event_jButton2_saveActionPerformed

    //validation
    private void jButton1_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_newActionPerformed
        // TODO add your handling code here:
        jTextField1_id.setText("");
        jTextField2_name.setText("");
        jTextField3_salary.setText("");
        jTextField4_subject.setText("");
        jDateChooser1_dob.setDate(null);
        jTextArea1_address.setText("");
        
        
        if (jTextField1_id.getText().toString().equals("") ||
           jTextField2_name.getText().toString().equals("")    
                )
            
        {
//            JOptionPane.showMessageDialog(null, "all fields are compulsary");
        }
        else{
            JOptionPane.showMessageDialog(null, "id :"+jTextField1_id.getText().toString());
            JOptionPane.showMessageDialog(null, "id :"+jTextField2_name.getText().toString());
        }
    }//GEN-LAST:event_jButton1_newActionPerformed

    //logic to edit or update the teacher information
    private void jButton3_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_updateActionPerformed
        // TODO add your handling code here:
        if (jTextField1_id.getText().toString().equals("") ||
            jTextField2_name.getText().toString().equals("") || 
            jTextField3_salary.getText().toString().equals("") ||
            jTextField4_subject.getText().toString().equals("") ||
            jTextArea1_address.getText().toString().equals("")
            )
            
        {
            JOptionPane.showMessageDialog(null, "all fields are compulsary");
        }
        else{
            try{
                Connection conn=getMySqlConnection();
                String query="update teacher set name=?, salary=?, dob=?, address=?, subject=? where id=?";
                PreparedStatement ps=conn.prepareStatement(query);
               
                ps.setString(1,jTextField2_name.getText().toString());
                ps.setFloat(2, Float.parseFloat(jTextField3_salary.getText().toString()));
                
                SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
                String dob1=sdf.format(jDateChooser1_dob.getDate());
                ps.setString(3,dob1);
                
                ps.setString(4,jTextField4_subject .getText().toString());
                ps.setString(5,jTextArea1_address.getText().toString());
                
                 ps.setInt(6, Integer.parseInt(jTextField1_id.getText().toString()));
                
                int res=ps.executeUpdate();
                fillTable();// fillTable() call to display the data after newly insertred teacher in table
                if (res>=1) {
                    JOptionPane.showMessageDialog(null, res+"teacher updated successfully to database"+
                            jTextField2_name.getText().toString());
                }else{
                    JOptionPane.showMessageDialog(null, "teacher Insertion Failed ....");
                }
                if (ps!=null){
                    ps.close();
                }
                if (conn!=null){
                    conn.close();
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "error in update : "+e);
            }       
            // clear the fileds
            jTextField1_id.setText("");
            jTextField2_name.setText("");
            jTextField3_salary.setText("");
            jTextField4_subject.setText("");
            jDateChooser1_dob.setDate(null);
            jTextArea1_address.setText("");
            
        }
    }//GEN-LAST:event_jButton3_updateActionPerformed

    // deete details from database
    private void jButton4_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_deleteActionPerformed
        // TODO add your handling code here:
        if (jTextField1_id.getText().toString().equals(""))
            
        {
            JOptionPane.showMessageDialog(null, "all fields are compulsary");
        }
        else{
            try{
                Connection conn=getMySqlConnection();
                String query="delete from teacher where id=?";
                PreparedStatement ps=conn.prepareStatement(query);
                ps.setInt(1, Integer.parseInt(jTextField1_id.getText().toString()));
                
                int res=ps.executeUpdate();
                fillTable();// fillTable() call to display the data after newly insertred teacher in table
                if (res>=1) {
                    JOptionPane.showMessageDialog(null, res+"teacher deleted successfully to database"+
                            "id : "+jTextField1_id.getText().toString());
                }else{
                    JOptionPane.showMessageDialog(null, "teacher deletion Failed ....");
                }
                if (ps!=null){
                    ps.close();
                }
                if (conn!=null){
                    conn.close();
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "error  in delete : "+e);
            }       
            // clear the fileds
            jTextField1_id.setText("");
            jTextField2_name.setText("");
            jTextField3_salary.setText("");
            jTextField4_subject.setText("");
            jDateChooser1_dob.setDate(null);
            jTextArea1_address.setText("");
            
        }
    }//GEN-LAST:event_jButton4_deleteActionPerformed

    // when user click on the table then take the data of that rows and fills in the fields
    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        int index=jTable.getSelectedRow();
        showItemToFields(index);
    }//GEN-LAST:event_jTableMouseClicked

    // search the faculty by their name
    private void jTextField1_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_searchKeyReleased
        // TODO add your handling code here: 
        ArrayList<teacher_bean> al=null;
                al=new ArrayList<teacher_bean>();
       String val=jTextField1_search.getText().toString();
        try {
            Connection conn=getMySqlConnection();
            //String query="select * from teacher where (name like '%"+val+"%')";
            String query="select * from teacher where name like '%"+val+"%'";
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery(query);
            teacher_bean teacher;
            while (rs.next()) {
                teacher =new teacher_bean(Integer.parseInt(rs.getString(1)),rs.getString("name"),
                        Float.parseFloat(rs.getString(3)), rs.getString(4), rs.getString("address"),
                        rs.getString(6));                
                al.add(teacher);
              }
            if (st!=null){
                    st.close();
                }
            if (conn!=null){
                    conn.close();
                }  
            
            // search teacher added to the databases
            DefaultTableModel model=(DefaultTableModel)jTable.getModel();
            model.setRowCount(0); // Empty/clear the table
            Object[] row=new Object[6];
            for (int i = 0; i < al.size(); i++) {
                row[0]=al.get(i).getId();
                row[1]=al.get(i).getName();
                row[2]=al.get(i).getSalary();
                row[3]=al.get(i).getDob();
                row[4]=al.get(i).getAddress();
                row[5]=al.get(i).getSubject();
                model.addRow(row);
            } 
            
            
        } catch (Exception e) {
            System.out.println("error at serch time : "+e);
        }
        
    }//GEN-LAST:event_jTextField1_searchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacher_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacher_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacher_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacher_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacher_window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_new;
    private javax.swing.JButton jButton2_save;
    private javax.swing.JButton jButton3_update;
    private javax.swing.JButton jButton4_delete;
    private com.toedter.calendar.JDateChooser jDateChooser1_dob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1_address;
    private javax.swing.JTextField jTextField1_id;
    private javax.swing.JTextField jTextField1_search;
    private javax.swing.JTextField jTextField2_name;
    private javax.swing.JTextField jTextField3_salary;
    private javax.swing.JTextField jTextField4_subject;
    // End of variables declaration//GEN-END:variables

    void Setvisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
